[build-system]
build-backend = "uv_build"
requires = ["uv_build<1"] # check tool.uv.required-version for tighter version constraints

[dependency-groups]
dev = [
    "pre-commit==4.6.1",
    "pyrefly==1.2.0",
    "pytest==9.1.1",
    "pytest-cov==7.1.0",
    "trcks[pyrefly]", # check project.dependencies for version
]

[project]
classifiers = ["Private :: Do Not Upload"]
dependencies = [
    "cyclopts==4.22.5",
    "trcks==0.6.2",
]
description = "Example CLI application that uses the trcks library for type-safe railway-oriented programming in Python 🚂🐍"
license = "MIT"
license-files = ["LICEN[CS]E*"]
name = "rtw"
requires-python = "~=3.14.0"
version = "1.2.3"

[project.scripts]
rtw = "rtw.user_interface:app"

[tool.pyrefly]
enabled-ignores = ["pyrefly"]
preset = "all"

[tool.pytest.ini_options]
addopts = "--cov=rtw --cov-fail-under=100 --cov-report=term-missing --import-mode=importlib"
filterwarnings = ["error"]

[tool.ruff.lint]
ignore = [
    "COM812", # "may cause conflicts when used with the formatter"
    "CPY001", # would require copyright notice on all files
    "D1", # would complain about missing docstrings
]
select = ["ALL"]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-decorators = ["cyclopts.App.default"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["INP001", "S101"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.uv]
add-bounds = "exact"
required-version = "~=0.12.0"
