name: Run tests and type checks
description: Executes the test suite and a static type checker.
inputs:
  locked:
    default: "true"
    description: Whether to assert that uv.lock remains unchanged during `uv sync`.
    required: true
  resolution-strategy:
    default: highest
    description: Strategy used by uv when selecting between different versions for a given package requirement.
    required: true
runs:
  using: composite
  steps:
    - env:
        LOCKED: ${{ fromJSON(inputs.locked) && '--locked' || '' }}
        RESOLUTION_STRATEGY: ${{ inputs.resolution-strategy }}
      run: uv sync --all-extras ${LOCKED} --resolution=${RESOLUTION_STRATEGY}
      shell: bash
    - run: uv run --no-sync pyright
      shell: bash
    - run: uv run --no-sync pytest
      shell: bash
