name: CI

on:
  - push

permissions: { }

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: christophgietl/uv-actions/set-up-uv@d149c21ae8654b9c19faae10433a5674e0094d3b # 2026.5.4
      - run: uv build --verbose
  lint-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: christophgietl/uv-actions/set-up-uv@d149c21ae8654b9c19faae10433a5674e0094d3b # 2026.5.4
        with:
          install-and-cache-dependencies: true
      - uses: christophgietl/uv-actions/set-up-pre-commit@d149c21ae8654b9c19faae10433a5674e0094d3b # 2026.5.4
        with:
          cache-key-suffix: ${{ matrix.os }}
      - run: uv run --no-sync pre-commit run --all-files --show-diff-on-failure
      - run: uv run --no-sync mypy
      - run: uv run --no-sync pyright
      - run: uv run --no-sync pytest
