name: CI

on:
  - push

permissions: { }

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: christophgietl/uv-actions/set-up-uv@c84085700a4d21a4b7c3ea35704aaa6454ebc72f # 2026.7.13
      - run: uv build --verbose
  lint-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: christophgietl/uv-actions/set-up-uv@c84085700a4d21a4b7c3ea35704aaa6454ebc72f # 2026.7.13
        with:
          install-and-cache-dependencies: true
      - uses: christophgietl/uv-actions/set-up-pre-commit@c84085700a4d21a4b7c3ea35704aaa6454ebc72f # 2026.7.13
        with:
          cache-key-suffix: ${{ matrix.os }}
      - run: uv run --no-sync pre-commit run --all-files --show-diff-on-failure
      - run: uv run --no-sync mypy
      - run: uv run --no-sync pytest
